# Refs:
# - https://doc.rust-lang.org/cargo/reference/manifest.html
# - https://doc.rust-lang.org/cargo/guide/project-layout.html
# - https://doc.rust-lang.org/cargo/reference/cargo-targets.html

[package]
name = "paddington"
version = "0.0.1"
authors = ["ğŸ·ğŸ› Lee Ball <lee.cat.ball@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/catleeball/Paddington"
repository = "https://github.com/catleeball/Paddington"
description = "Add padding or crop an image to fit an aspect ratio."

[dependencies]
lazy_static = "^1.4.0"
regex = "^1.4.3"
log = "^0.4.13"
stderrlog = "^0.5.1"
structopt = "^0.3.21"