[package]
name = "paddington"
version = "0.0.1"
authors = ["ğŸ·ğŸ› Lee Ball <lee.cat.ball@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
